### ISSUE TITLE
I get an error when running the command in windows

### ISSUE THREAD

**Issue by java-boy** [lgdd/liferay-starter#11]
I get an error when running the command in Windows.
I used other versions of Liferay too, but still getting error!
I tried portal-7.2-ga2, dxp-7.2-sp3, dxp-7.3-ep6, portal-7.3-ga5 but I always get error.
For 7.3 I get an error that tells it can not find some files to download.

And here is the error for 7.2:

E:\liferayTest>>mkdir liferay-project && copy liferay-project.zip liferay-project && cd liferay-project && jar xvf liferay-project.zip && del liferay-project.zip && gradlew.bat initBundle
        1 file(s) copied.
 inflated: build.gradle
 inflated: gradlew.bat
 inflated: modules/my-rest/build.gradle
 inflated: modules/my-rest/bnd.bnd
 inflated: modules/my-rest/src/main/java/org/acme/my/rest/application/MyRestApplication.java
  created: modules/my-rest/src/main/resources/
 inflated: modules/my-rest/.gitignore
 inflated: modules/my-react/.npmbundlerrc
 inflated: modules/my-react/README.md
 inflated: modules/my-react/assets/css/styles.css
 inflated: modules/my-react/assets/.placeholder
 inflated: modules/my-react/features/configuration.json
 inflated: modules/my-react/features/localization/Language.properties
 inflated: modules/my-react/.npmignore
 inflated: modules/my-react/.npmbuildrc
 inflated: modules/my-react/.babelrc
 inflated: modules/my-react/src/AppComponent.js
 inflated: modules/my-react/src/index.js
 inflated: modules/my-react/package.json
 inflated: modules/my-react/.gitignore
 inflated: modules/my-react/.npmrc
 inflated: modules/my-rest-builder/build.gradle
 inflated: modules/my-rest-builder/my-rest-builder-client/build.gradle
 inflated: modules/my-rest-builder/my-rest-builder-client/bnd.bnd
 inflated: modules/my-rest-builder/my-rest-builder-test/build.gradle
 inflated: modules/my-rest-builder/my-rest-builder-test/bnd.bnd
 inflated: modules/my-rest-builder/my-rest-builder-impl/build.gradle
 inflated: modules/my-rest-builder/my-rest-builder-impl/bnd.bnd
 inflated: modules/my-rest-builder/my-rest-builder-impl/rest-openapi.yaml
 inflated: modules/my-rest-builder/my-rest-builder-impl/rest-config.yaml
 inflated: modules/my-rest-builder/my-rest-builder-api/build.gradle
 inflated: modules/my-rest-builder/my-rest-builder-api/bnd.bnd
 inflated: modules/my-rest-builder/.gitignore
 inflated: modules/my-mvc-portlet/build.gradle
 inflated: modules/my-mvc-portlet/bnd.bnd
 inflated: modules/my-mvc-portlet/src/main/java/org/acme/my/mvc/portlet/portlet/MyMvcPortlet.java
 inflated: modules/my-mvc-portlet/src/main/java/org/acme/my/mvc/portlet/constants/MyMvcPortletKeys.java
 inflated: modules/my-mvc-portlet/src/main/resources/content/Language.properties
 inflated: modules/my-mvc-portlet/src/main/resources/META-INF/resources/init.jsp
 inflated: modules/my-mvc-portlet/src/main/resources/META-INF/resources/css/main.scss
 inflated: modules/my-mvc-portlet/src/main/resources/META-INF/resources/view.jsp
 inflated: modules/my-mvc-portlet/.gitignore
 inflated: gradle.properties
 inflated: platform.bndrun
 inflated: gradle-local.properties
 inflated: settings.gradle
 inflated: gradlew
 inflated: .blade.properties
 inflated: configs/common/.touch
 inflated: configs/local/portal-ext.properties
 inflated: configs/dev/portal-ext.properties
 inflated: configs/prod/osgi/configs/com.liferay.portal.search.elasticsearch.configuration.ElasticsearchConfiguration.config
 inflated: configs/prod/portal-ext.properties
 inflated: configs/uat/osgi/configs/com.liferay.portal.search.elasticsearch.configuration.ElasticsearchConfiguration.config
 inflated: configs/uat/portal-ext.properties
 inflated: configs/docker/.touch
 inflated: .gitignore
  created: themes/
 inflated: gradle/wrapper/gradle-wrapper.jar
 inflated: gradle/wrapper/gradle-wrapper.properties
Starting a Gradle Daemon, 1 incompatible and 1 stopped Daemons could not be reused, use --status for details

> Task :initBundle FAILED
Exception in thread "main" java.io.EOFException
        at org.apache.commons.compress.compressors.gzip.GzipCompressorInputStream.read(GzipCompressorInputStream.java:303)
        at org.apache.commons.compress.archivers.tar.TarArchiveInputStream.read(TarArchiveInputStream.java:639)
        at java.base/java.io.InputStream.transferTo(InputStream.java:704)
        at java.base/java.nio.file.Files.copy(Files.java:3077)
        at com.liferay.portal.tools.bundle.support.internal.util.FileUtil._writeArchiveEntryFile(FileUtil.java:511)
        at com.liferay.portal.tools.bundle.support.internal.util.FileUtil._untar(FileUtil.java:444)
        at com.liferay.portal.tools.bundle.support.internal.util.FileUtil.unpack(FileUtil.java:271)
        at com.liferay.portal.tools.bundle.support.commands.InitBundleCommand.execute(InitBundleCommand.java:58)
        at com.liferay.portal.tools.bundle.support.BundleSupport.main(BundleSupport.java:73)

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':initBundle'.
> Process 'command 'C:\Program Files\Java\jdk-11.0.6\bin\java.exe'' finished with non-zero exit value 1

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 26s
2 actionable tasks: 2 executed

**Comment by lgdd** [comment]
Hi @java-boy! Thanks for your report!

This error might happen when the downloaded bundle is corrupted, likely due to network errors (either from the client side or server side, and it happened to me few days ago without using Liferay Starter).

Could you try to delete everything under `C:\Users\<your_username>\.liferay\bundles` and run the command again please?

**Comment by java-boy** [comment]
@lgdd Thanks a lot Louis, it worked for me. ;)
